In [84]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader, random_split
import numpy as np
import pandas as pd

In [85]:
class protein_dataset(Dataset):
    pass

In [86]:
class EnzymeDataset(Dataset):
    def __init__(self, data_X, data_Y):
        self.getAAmap()
        self.data_X = data_X
        self.data_Y = data_Y
        
    
    def __len__(self):
        return len(self.data_X)
    
    
    def getAAmap(self):
        aa_vocab = ['A', 'C', 'D', 'E', 
                    'F', 'G', 'H', 'I', 
                    'K', 'L', 'M', 'N', 
                    'P', 'Q', 'R', 'S',
                    'T', 'V', 'W', 'X', 
                    'Y', '_']
        map = {}
        for i, char in enumerate(aa_vocab):
            baseArray = np.zeros(len(aa_vocab)-1)
            if char != '_':
                baseArray[i] = 1
            map[char] = baseArray
        self.map = map
        return

        
    def convert2onehot(self, single_seq):
        single_onehot = []
        for x in single_seq:
            single_onehot.append(self.map[x])
        return np.asarray(single_onehot)
    
    
    def __getitem__(self, idx):
        x = self.data_X[idx]
        x = self.convert2onehot(x)
        y = self.data_Y[idx]
        
        
        x = x.reshape((1,) + x.shape)
        y = y.reshape(-1)
        return x, y

In [87]:
AA_LIST = ['-', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
MAX_LEN= 1000



In [88]:
# I could just save OHE and convert in form of torch.from_numpy but i would have to load each fasta again. I want to do it properly
# Datasets from pytorch need several key methods
# __getitem__, __len__, __init__

In [89]:
class protein_seq(Dataset):
    # probably OHE every sequence as it is retrieved?
    def __init__(self, seq, label):
        self.seq = seq
        self.label = label

    def __len__(self):
        if len(self.seq) != len(self.label):
            raise Exception("Count of sequences and labels should be the same")
            
        return len(self.seq)

    def ohe_seq(self):
        

SyntaxError: incomplete input (2988258343.py, line 14)

In [90]:
def convert2onehot(single_seq, mapper):
    single_onehot = []
    for x in single_seq:
        single_onehot.append(mapper[x])
    return np.asarray(single_onehot)
    

In [91]:
    def getAAmap():
        aa_vocab = ['A', 'C', 'D', 'E', 
                    'F', 'G', 'H', 'I', 
                    'K', 'L', 'M', 'N', 
                    'P', 'Q', 'R', 'S',
                    'T', 'V', 'W', 'X', 
                    'Y', '_']
        map = {}
        for i, char in enumerate(aa_vocab):
            baseArray = np.zeros(len(aa_vocab)-1)
            if char != '_':
                baseArray[i] = 1
            map[char] = baseArray
        return map

In [92]:
AAmap = getAAmap()
AAmap

{'A': array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'C': array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'D': array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'E': array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'F': array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'G': array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'H': array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'I': array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'K': array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 'L': array([0., 0., 0., 0., 0., 0., 

In [93]:
seq = "AACCCDEE"
ohe_seq = convert2onehot(seq, AAmap)


In [94]:
# yeah this is the correct shape, but previous sklearn approaches wanted something different
test = ohe_seq.reshape((1,) + ohe_seq.shape) # from (8, 21) => (1, 8, 21) so now 3d tensor
print(test, test.shape)
tensor = torch.from_numpy(test.astype("int8"))
print(tensor)
# 

[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]] (1, 8, 21)
tensor([[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       

In [95]:
AA_LIST = ['-', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
MAX_LEN= 1000
# CAN DO IT MORE ELEGANTY BUT THIS IS WHAT IWANT NOW

class protein_seq(Dataset):
    # probably OHE every sequence as it is retrieved?
    def __init__(self, seq: np.ndarray, label: np.ndarray):
        self.seq = seq
        self.label = label

        self.MAX_LEN = 1000
        self.mask = "-"
        self.vocab_mapping(AA_LIST)

    def __len__(self):
        if len(self.seq) != len(self.label):
            raise Exception("Count of sequences and labels should be the same")
            
        return len(self.seq)

    def pad(self, single_seq):
        pad_seq = self.seq[:self.MAX_LEN] if len(single_seq) > self.MAX_LEN else single_seq + "-" * (self.MAX_LEN - len(single_seq))

        return pad_seq

    def vocab_mapping(self, vocab):
        mapping = {}
        base = np.zeros(len(vocab))
        for i, x in enumerate(vocab):
            if x != '-':
                base[i] = 1
            mapping[x] = base
        self.mapper = mapping

        return 

    def ohe(self, seq):
        ohe_seq = []
        for i, x in enumerate(seq):
            if x in AA_LIST:
                ohe_seq.append(self.mapper[x])
            else:
                ohe_seq.append(self.mapper["-"])
        ohe_seq_np = np.asarray(ohe_seq).astype("int8")

        return ohe_seq_np

    def __getitem__(self, idx):
        x = self.seq[idx]
        x = self.pad(x)
        x = self.ohe(x)
        y = self.label[idx]

        x = x.reshape((1,) + x.shape)
        y = y.reshape(-1)
        
        return x, y

In [96]:
labels = np.array([0, 1])
labels

array([0, 1])

In [97]:
labels.shape

(2,)

In [98]:
new = labels.reshape(-1)


In [99]:
new.shape

(2,)

In [133]:
# Based on DeepTFactor, without subnetworks
# One sequence is (1000 , 21) shape and as a tensor (1, 1000 ,21), so only 1 "channel" in batches of 64 so (64, 1, 1000, 21)
# Seems like PyTorch objects allow for general flexibility in input shape for Layers 
# softmax for probabilty of last input layer
class CNN_Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn1 = nn.Conv2d(1, 64, 1, 1)
        self.batchnorm1_cnn = nn.BatchNorm2d(num_features = 64)
        self.cnn2 = nn.Conv2d(64, 32, 1, 1)
        self.batchnorm2_cnn = nn.BatchNorm2d(num_features = 32)
        self.fcn1 = nn.Linear(128*1*21, 16)
        self.bn1 = nn.BatchNorm1d(num_features = 16)
        self.fcn2 = nn.Linear(16, 8)
        self.bn2 = nn.BatchNorm1d(num_features = 8)
        self.fcn3 = nn.Linear(8, 4)
        self.bn3 = nn.BatchNorm1d(num_features = 4)
        self.fcn4 = nn.Linear(4, 1)
        self.bn4 = nn.BatchNorm1d(num_features = 1)
        self.softmax = nn.Softmax()
        # Think about chaning kernel_size to do something different
        self.pool = nn.MaxPool2d(kernel_size = (1000,1), stride = 1)
        self.relu = nn.ReLU()
        self.out_act = nn.Sigmoid()
        self.dropout = nn.Dropout(p=0.15)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.relu(self.batchnorm1_cnn(self.cnn1(x)))
        #print(x.shape)
        x = self.relu(self.batchnorm2_cnn(self.cnn2(x)))
        print(x.shape)
        x = self.pool(x)
        print(x.shape)
        x = x.view(-1, 128 * 1 * 21)
        #print(x.shape)
        x = self.relu(self.bn1(self.fcn1(x)))
        #print(x.shape)
        x = self.relu(self.bn2(self.fcn2(x)))
        #print(x.shape)
        x = self.relu(self.bn3(self.fcn3(x)))
        #print(x.shape)
        x = self.out_act(self.bn4(self.fcn4(x)))
        #print(x.shape)
        # now i get why this might be awful to do argmax for prediction
        # this might lead to no real high values for each neuron 
        # for class if index is 0 
        #x = torch.as_tensor(torch.argmax(x))
        print(x)
        print(x[0])
        return x

    def predicted(self, x):
        pass
        

In [134]:
# Now main loop or real data loading
# Read training data:
data = pd.read_table("C:/Users/Fabian/Desktop/TFs_balanced.tsv", index_col = 0)[["seqs","marker"]]
#data["label"] = (data
#                .groupby("marker")["marker"]
#                 .transform(lambda x: 1 if data[x] == "TF" else 0)
#                )
def convert_markers(row):
    if row["marker"] == "TF":
        return 1
    if row["marker"] == "NoTF":
        return 0
    else:
        return None

data["label"] = data.apply(convert_markers, axis = 1)

In [135]:
data

seqs marker  label
0      MAFSAEDVLKEYDRRRRMEALLLSLYYPNDRKLLDYKEWSPPRVQV...     TF      1
1      MSFQRDYESEWNAALIEEYGEGGSGFSHGRFASLRMCEQRLYRPPG...     TF      1
2      MERLKRMSVFAKVVEFGSFTAAARQLQMSVSSISQTVSKLEDELQV...     TF      1
3      MERLKRMSVFAKVVEFGSFTAAARQLQMSVSSISQTVSKLEDELQV...     TF      1
4      MERLKRMSVFAKVVEFGSFTAAARQLQMSVSSISQTVSKLEDELQV...     TF      1
...                                                  ...    ...    ...
13285  MHPKRRLCWCLPASGAWAFMLTSLIADTTACESEERLFHKLFSRYN...   NoTF      0
13286  MLTSKGQGFLHGGLCLWLCVFTPFFKGCVGCATEERLFHKLFSHYN...   NoTF      0
13287  MLNSRDQGNLHSGLCLWLCGFLALFKGSTGCESEEQLFHRLFAHYN...   NoTF      0
13288  MLTSKGQGFLHGGLCLWLCVFTPFFKGCVGCATEERLFHKLFSHYN...   NoTF      0
13289  MLNGWGRGDLRSGLCLWICGFLAFFKGSRGCVSEEQLFHTLFAHYN...   NoTF      0

[13290 rows x 3 columns]

In [136]:
torch_data = protein_seq(data["seqs"], data["label"])

In [137]:
torch_data[12888]

(array([[[0, 1, 1, ..., 1, 1, 1],
         [0, 1, 1, ..., 1, 1, 1],
         [0, 1, 1, ..., 1, 1, 1],
         ...,
         [0, 1, 1, ..., 1, 1, 1],
         [0, 1, 1, ..., 1, 1, 1],
         [0, 1, 1, ..., 1, 1, 1]]], dtype=int8),
 array([0], dtype=int64))

In [138]:
proteinDataLoader = DataLoader(torch_data, batch_size = 2, shuffle = True)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu


In [139]:
model = CNN_Classifier()
model.to(device)
print(proteinDataLoader)

In [140]:
generator1 = torch.Generator().manual_seed(42)
train_dataset, test_dataset = random_split(torch_data, [round(len(torch_data) * 0.8), round(len(torch_data) * 0.2)], generator1)

In [147]:
proteinDataLoader = DataLoader(train_dataset, batch_size = 2, shuffle = True)
#train_features, train_labels = next(iter(train_proteinDataLoader))
#train_features = train_features.to(torch.float32)
#train_labels = train_labels.to(torch.float32)
proteinDataLoader_test = DataLoader(test_dataset, batch_size = 2, shuffle = True)

In [148]:
epochs = 5
loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(params = model.parameters(), lr = 0.01)

In [149]:
torch.manual_seed(42)

# Set the number of epochs 

for epoch in range(epochs):
    ### Training
    model.train() # train mode is on by default after construction

    # 1. Forward pass
    for x, y in proteinDataLoader:
        x = x.to(torch.float32)
        y = y.to(torch.float32)
        y = y.to(device)
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    #y_pred = model(train_features)
    #print(y_pred)
    #print(y_pred.shape)
    #print(train_labels.shape)

    # 2. Calculate loss
    #loss = loss_fn(y_pred, train_labels)

    # 3. Zero grad optimizer
    #optimizer.zero_grad()

    # 4. Loss backward
    #loss.backward()

    # 5. Step the optimizer
    #optimizer.step()

    ### Testing
    model.eval() # put the model in evaluation mode for testing (inference)
    # 1. Forward pass
    with torch.inference_mode():
        for x, y in proteinDataLoader_test:
            x = x.to(torch.float32)
            y = y.to(torch.float32)
            test_pred = model(x)
    
            # 2. Calculate the loss
            test_loss = loss_fn(test_pred, y)

        print(f"Epoch: {epoch} | Train loss: {loss} | Test loss: {test_loss}")

torch.Size([2, 128, 1000, 21])
torch.Size([2, 128, 1, 21])
tensor([[0.4991],
        [0.4991]], grad_fn=<SigmoidBackward0>)
tensor([0.4991], grad_fn=<SelectBackward0>)
torch.Size([2, 128, 1000, 21])
torch.Size([2, 128, 1, 21])
tensor([[0.4978],
        [0.4978]], grad_fn=<SigmoidBackward0>)
tensor([0.4978], grad_fn=<SelectBackward0>)
torch.Size([2, 128, 1000, 21])
torch.Size([2, 128, 1, 21])
tensor([[0.4966],
        [0.4966]], grad_fn=<SigmoidBackward0>)
tensor([0.4966], grad_fn=<SelectBackward0>)
torch.Size([2, 128, 1000, 21])
torch.Size([2, 128, 1, 21])
tensor([[0.4966],
        [0.4966]], grad_fn=<SigmoidBackward0>)
tensor([0.4966], grad_fn=<SelectBackward0>)
torch.Size([2, 128, 1000, 21])
torch.Size([2, 128, 1, 21])
tensor([[0.4966],
        [0.4966]], grad_fn=<SigmoidBackward0>)
tensor([0.4966], grad_fn=<SelectBackward0>)
torch.Size([2, 128, 1000, 21])
torch.Size([2, 128, 1, 21])
tensor([[0.4966],
        [0.4966]], grad_fn=<SigmoidBackward0>)
tensor([0.4966], grad_fn=<SelectBack

KeyboardInterrupt: 

In [ ]:
torch.set_grad_enabled(True)

In [ ]:
print(model)

In [ ]:
for x, _  in train_proteinDataLoader:
    x = x.to(torch.float32)

In [54]:
test = torch.randn((64, 1, 1000, 21))

In [198]:
test.view(32, -1).shape

torch.Size([32, 42000])

In [60]:
test_pool = torch.nn.MaxPool2d(kernel_size = (1000,1), stride = 1)
test = test_pool(test)
test.shape

RuntimeError: Given input size: (1x1x21). Calculated output size: (1x-998x21). Output size is too small

In [152]:
test = test.view(-1, 1000 * 21)
print(test.shape)

torch.Size([64, 21000])


In [62]:
len(train_proteinDataLoader)

167

In [91]:
a = torch.zeros(64, 1, 1000,21)

In [92]:
a

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [96]:
b = torch.randn(1344000, 1)

In [97]:
b = b.view(64, -1)

In [99]:
b.shape

torch.Size([64, 21000])

In [100]:
class DeepTFactor(nn.Module):
    def __init__(self, out_features=[0]):
        super(DeepTFactor, self).__init__()
        self.explainECs = out_features
        self.layer_info = [[4, 4, 16], [12, 8, 4], [16, 4, 4]]
        self.cnn0 = CNN(self.layer_info)
        self.fc1 = nn.Linear(in_features=128*3, out_features=512)
        self.bn1 = nn.BatchNorm1d(num_features=512)
        self.fc2 = nn.Linear(in_features=512, out_features=len(out_features))
        self.bn2 = nn.BatchNorm1d(num_features=len(out_features))
        self.out_act = nn.Sigmoid()
        self.relu = nn.ReLU()
        self.init_weights()


    def init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.xavier_uniform_(m.weight)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)

        
    def forward(self, x):
        x = self.cnn0(x)
        x = x.view(-1, 128*3)
        x = self.relu(self.bn1(self.fc1(x)))
        x = self.out_act(self.bn2(self.fc2(x)))
        return x


class CNN(nn.Module):
    '''
    Use second level convolution.
    channel size: 4 -> 16 
                  8 -> 12
                  16 -> 4
    '''
    def __init__(self, layer_info):
        super(CNN, self).__init__()
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.1)

        self.layers = nn.ModuleList()
        pooling_sizes = []
        for subnetwork in layer_info:
            pooling_size = 0
            self.layers += [self.make_subnetwork(subnetwork)]
            for kernel in subnetwork:
                pooling_size += (-kernel + 1)
            pooling_sizes.append(pooling_size)
              
        if len(set(pooling_sizes)) != 1:
            raise "Different kernel sizes between subnetworks"
        pooling_size = pooling_sizes[0]
        num_subnetwork = len(layer_info)
        
        self.conv = nn.Conv2d(in_channels=128*num_subnetwork, out_channels=128*3, kernel_size=(1,1))
        self.batchnorm = nn.BatchNorm2d(num_features=128*3)
        self.pool = nn.MaxPool2d(kernel_size=(1000+pooling_size,1), stride=1)


    def make_subnetwork(self, subnetwork):
        subnetworks = []
        for i, kernel in enumerate(subnetwork):
            if i == 0:
                subnetworks.append(
                    nn.Sequential(
                        nn.Conv2d(in_channels=1, out_channels=128, kernel_size=(kernel, 21)),
                        nn.BatchNorm2d(num_features=128),
                        nn.ReLU(),
                        nn.Dropout(p=0.1)
                    )
                )
            else:
                subnetworks.append(
                    nn.Sequential(
                        nn.Conv2d(in_channels=128, out_channels=128, kernel_size=(kernel, 1)),
                        nn.BatchNorm2d(num_features=128),
                        nn.ReLU(),
                        nn.Dropout(p=0.1)
                    )
                )
        return nn.Sequential(*subnetworks)

        
    def forward(self, x):
        xs = []
        for layer in self.layers:
            xs.append(layer(x))
        x = torch.cat(xs, dim=1)
        x = self.relu(self.batchnorm(self.conv(x)))
        x = self.pool(x)
        return x

In [ ]:
class CNN_Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn1 = nn.Conv2d(1, 64, 1, 1)
        self.batchnorm1_cnn = nn.BatchNorm2d(num_features = 64)
        self.cnn2 = nn.Conv2d(64, 32, 1, 1)
        self.batchnorm2_cnn = nn.BatchNorm2d(num_features = 32)
        self.cnn3 = nn.Conv2d(32, 16, 1, 1)
        self.cnn4 = nn.Conv2d(16, 8, 1, 1)
        self.cnn4 = nn.Conv2d(8, 16, 1, 1)
        self.cnn5 = nn.Conv2d(16, 32, 1, 1)
        self.cnn6 = nn.Conv2d(32, 64, 1, 1)
        self.fcn1 = nn.Linear(128*1*21, 16)
        self.bn1 = nn.BatchNorm1d(num_features = 16)
        self.fcn2 = nn.Linear(16, 8)
        self.bn2 = nn.BatchNorm1d(num_features = 8)
        self.fcn3 = nn.Linear(8, 4)
        self.bn3 = nn.BatchNorm1d(num_features = 4)
        self.fcn4 = nn.Linear(4, 1)
        self.bn4 = nn.BatchNorm1d(num_features = 1)
        self.softmax = nn.Softmax()
        # Think about chaning kernel_size to do something different
        self.pool = nn.MaxPool2d(kernel_size = (1000,1), stride = 1)
        self.relu = nn.ReLU()
        self.out_act = nn.Sigmoid()
        self.dropout = nn.Dropout(p=0.15)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.relu(self.batchnorm1_cnn(self.cnn1(x)))
        #print(x.shape)
        x = self.relu(self.batchnorm2_cnn(self.cnn2(x)))
        print(x.shape)
        x = self.pool(x)
        print(x.shape)
        x = x.view(-1, 128 * 1 * 21)
        #print(x.shape)
        x = self.relu(self.bn1(self.fcn1(x)))
        #print(x.shape)
        x = self.relu(self.bn2(self.fcn2(x)))
        #print(x.shape)
        x = self.relu(self.bn3(self.fcn3(x)))
        #print(x.shape)
        x = self.out_act(self.bn4(self.fcn4(x)))
        #print(x.shape)
        # now i get why this might be awful to do argmax for prediction
        # this might lead to no real high values for each neuron 
        # for class if index is 0 
        #x = torch.as_tensor(torch.argmax(x))
        print(x)
        print(x[0])
        return x

    def predicted(self, x):
        pass
        